//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<System.TimeSpan> TimeIn1 { get; set; }
        public Nullable<System.TimeSpan> TimeOut1 { get; set; }
        public Nullable<System.TimeSpan> TimeIn2 { get; set; }
        public Nullable<System.TimeSpan> TimeOut2 { get; set; }
        public Nullable<System.TimeSpan> TimeIn3 { get; set; }
        public Nullable<System.TimeSpan> TimeOut3 { get; set; }
    }
}
